- testKind: iperf
  numPolicies: 5
  numServices: 10
  numPods: 7
  duration: 10
  hostNetwork: false
  iterations: 1
  leaveStandingConfig: false
  TestNamespace: testns1
  Perf:
    direct: true
    service: true
    external: true
    ExternalIPOrFQDN: "a769dbaf0a7c14fe98e1d26a18fa5c19-444882487.us-west-2.elb.amazonaws.com"
    # ExternalIPOrFQDN: "34.213.205.24"
    TestPort: 32003

- testKind: thruput-latency
  numPolicies: 5
  numServices: 10
  numPods: 7
  duration: 10
  hostNetwork: false
  iterations: 1
  leaveStandingConfig: false
  TestNamespace: testns1
  Perf:
    direct: true
    service: true
    external: true
    ExternalIPOrFQDN: "a6c519e4e9d5a46d795e0d41bf82e93f-1429478103.us-west-2.elb.amazonaws.com"
    # ExternalIPOrFQDN: "ec2-34-213-205-24.us-west-2.compute.amazonaws.com"
    # ControlPort: 31106
    # TestPort: 32444
    # ExternalIPOrFQDN: "test-external-qperf.testns"
    ControlPort: 32000
    TestPort: 32221

- testKind: ttfr
  numPolicies: 100
  numServices: 10
  numPods: 7
  duration: 60
  hostNetwork: false
  iterations: 1
  leaveStandingConfig: false
  TestNamespace: testns1
  TTFRConfig:
    TestPodsPerNode: 53
    Rate: 2.5

- testKind: dnsperf
  TestNamespace: dnsperf
  numServices: 10
  iterations: 1
  leaveStandingConfig: false
  duration: 60
  DNSPerf:
    numDomains: 0
    RunStress: false
    TestDNSPolicy: false
    numTargetPods: 10
    targetType: service
